name = "WaveAcoustics"
uuid = "015e6fd1-d146-4073-8025-2809e47f770e"
version = "0.1.0"
authors = ["Bruno Alves do Carmo <bruno.carmo@ppgi.ufrj.br>"]

[workspace]
projects = ["docs"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1.6.3"
FixedSizeArrays = "1.2.0"
FunctionWrappers = "1.1.3"
GaussQuadrature = "0.5.8"
LinearAlgebra = "1.12.0"
Printf = "1.11.0"
SparseArrays = "1.12.0"
StaticArrays = "1.9.15"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
